force-app/main/default/objects/Lead/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha 2 Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Alpha_2_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Alpha_3_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_Code__c</fullName>
    <label>Alpha 3 Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Alpha_3_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Regional_Bloc__c.field-meta.xml
<CustomField>
    <fullName>Regional_Bloc__c</fullName>
    <label>Regional Bloc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Bloc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <label>Subregion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/LeadServiceTest.cls
@IsTest(SeeAllData=false)
private class LeadServiceTest {

    @IsTest
    static void addCountryInfoDetailTest() {
        //given
        LeadService leadServiceImpl = new LeadService(new CountryDaoMockImpl());
        Lead leadToInsert = new Lead(
                LastName = 'Test',
                Country = 'Czech Republic',
                Company = 'Test',
                LeadSource = 'Web',
                NumberOfEmployees = 10
        );

        //when
        Test.startTest();
        leadServiceImpl.addCountryInfoDetail(null, new List<Lead>{ leadToInsert });
        Test.stopTest();
        //then
        System.assertEquals('Europe', leadToInsert.Region__c);
        System.assertEquals('Central Europe', leadToInsert.Subregion__c);
        System.assertEquals('CZE', leadToInsert.Alpha_3_Code__c);
        System.assertEquals('CZ', leadToInsert.Alpha_2_Code__c);
        System.assertEquals('EU', leadToInsert.Regional_Bloc__c);
    }

    @IsTest
    static void triggerIntegrationTest() {
        insert new TestUtility.CountryFactory().getCzechRepublic();

        Lead testLead = new Lead(
                LastName = 'Test',
                Country = 'Czech Republic',
                Company = 'Test',
                LeadSource = 'Web',
                NumberOfEmployees = 10
        );
        insert testLead;

        Test.startTest();
        update testLead;
        Test.stopTest();
    }
}