force-app/main/default/objects/Country__c/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha 2 Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Alpha_3_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_Code__c</fullName>
    <label>Alpha 3 Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Regional_Bloc__c.field-meta.xml
<CustomField>
    <fullName>Regional_Bloc__c</fullName>
    <label>Regional Bloc</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha 2 Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Alpha_2_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Alpha_3_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_Code__c</fullName>
    <label>Alpha 3 Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Alpha_3_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Regional_Bloc__c.field-meta.xml
<CustomField>
    <fullName>Regional_Bloc__c</fullName>
    <label>Regional Bloc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Bloc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <label>Subregion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/LeadService.cls
public with sharing class LeadService {

    private final CountryDao countryDaoImpl;

    public LeadService(CountryDao countryDao) {
        countryDaoImpl = countryDao;
    }

    /**
     * Method adds Country Details to Lead record on insert and update
     *
     * @param oldMap - old Lead values
     * @param newList - new Lead values
     */
    public void addCountryInfoDetail(Map<Id, Lead> oldMap, List<Lead> newList) {
        Map<String, Country__c> countriesByName = countryDaoImpl.getAllCountriesByName();

        for (Lead lead : newList) {
            if ((oldMap == null || oldMap.get(lead.Id).Country != lead.Country) &&
                    countriesByName.get(lead.Country) != null) {

                lead.Alpha_2_Code__c = countriesByName.get(lead.Country).Alpha_2_Code__c;
                lead.Alpha_3_Code__c = countriesByName.get(lead.Country).Alpha_3_Code__c;
                lead.Capital_City__c = countriesByName.get(lead.Country).Capital_City__c;
                lead.Regional_Bloc__c = countriesByName.get(lead.Country).Regional_Bloc__c;
                lead.Region__c = countriesByName.get(lead.Country).Region__c;
                lead.Subregion__c = countriesByName.get(lead.Country).Subregion__c;
            }
        }
    }
}